version: '3.9'

services:
  mongodb:
    image: mongo:8.0.8
    container_name: mongodb
    hostname: mongodb
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:?}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:?}
    volumes:
      - mongodb-data:/data/mongodb

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongodb-gui
    restart: on-failure
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:?}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb-data: