"""21:51 19.04.2025

Revision ID: 5ad3dc6e45fc
Revises: db43f4416f5e
Create Date: 2025-04-19 21:51:27.518032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad3dc6e45fc'
down_revision: Union[str, None] = 'db43f4416f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_type', 'workout_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_type', 'workout_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
