"""14:18 16.04.2025

Revision ID: db43f4416f5e
Revises: 
Create Date: 2025-04-16 14:20:32.310432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db43f4416f5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_type',
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('workout_number', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_type')
    # ### end Alembic commands ###
